### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by paazmaya** [pocketjoso/specificity-graph#14]
Please provide a command line interface which could be used like:

```sh
specificity-graph create file.css [options]
specificity-graph update file.css
```

**Comment by pocketjoso** [comment]
@paazmaya @stefanjudis This functionality is now available as of `specificity-graph v0.1`. Feedback welcome!

**Comment by stefanjudis** [comment]
@pocketjoso nice!!! will hopefully give it a shot soon.

Thanks for your work. :bowtie:

**Comment by paazmaya** [comment]
Great, thank you!

**Comment by pocketjoso** [comment]
Thank @dhoko, he did most of the work. :)
