### ISSUE TITLE
Using as a module fails due to main pointing CLI

### ISSUE THREAD

**Issue by paazmaya** [pocketjoso/specificity-graph#21]
The `main` property of `package.json` should point to `lib/core.js` instead of the command line interface, which is used for `bin` property.
https://github.com/pocketjoso/specificity-graph/blob/master/package.json#L19

https://docs.npmjs.com/files/package.json#main

You might want to create an `index.js` which wraps all the different files from `lib/`, so that there would be a single point of entry (file) when used as `require()`.

**Comment by pocketjoso** [comment]
Thanks, I'll sort this out this weekend.

I would normally put the `index.js` file inside `lib` - is there any disadvantage in doing so?

**Comment by paazmaya** [comment]
No disadvantages that I would remember..
Might be even cleaner that way.

**Comment by pocketjoso** [comment]
The open PR (#22) makes the node module functional, although I'm not quite sure that what it does makes the most sense for a node module. Right now it will just do what the CLI does - writing specificity files to file (including a `html` file that displays the specificity graph). If @paazmaya has feedback on this I guess we'll open new issues and new PR's to solve them. :)

**Comment by paazmaya** [comment]
Thank you very much for your effort!
I will try it out next week..
