### ISSUE TITLE
CSS in media queries is ignored.

### ISSUE THREAD

**Issue by derheap** [pocketjoso/specificity-graph#24]
Any CSS inside a media query is ignored.
That way you can not judge CSS for responsive websites.
![bildschirmfoto 2015-07-17 um 12 04 09](https://cloud.githubusercontent.com/assets/5664700/8745019/f8d109c0-2c7b-11e5-9375-1896b37d1b08.png)

It should be analysed and the position of the media query should be marked in the graph.

**Comment by pocketjoso** [comment]
Hi @derheap - thanks for raising this issue, crazy that I never noticed that before. Will look into.

**Comment by derheap** [comment]
Thanx for the quick fix!
